services:
  - type: web
    name: affiliate-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    buildFilter:
      paths:
        - src/**
        - public/**
        - package.json
        - next.config.js
        - prisma/**
    disk:
      name: build-cache
      mountPath: /.next/cache
      sizeGB: 1
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: affiliate-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: affiliate-db
    plan: free 